blog/urls.py
from django.urls import path

from .views import (ArticleCreateView, ArticleDeleteView, ArticleDetailView,
                    ArticleListView, ArticleUpdateView)

urlpatterns = [
    path('', ArticleListView.as_view(), name='article-list'),
    path('create/', ArticleCreateView.as_view(), name='article-create'),
    path('<slug:slug>/', ArticleDetailView.as_view(), name='article-detail'),
    path('<slug:slug>/edit/', ArticleUpdateView.as_view(), name='article-edit'),
    path('<slug:slug>/delete/', ArticleDeleteView.as_view(), name='article-delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from pages.views import about_view, contact_view, home_view, search_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view),
    path('contact/', contact_view),
    path('about/', about_view),
    path('search/', search_view, name='search'),
    path('products/', include('products.urls')),
    path('blog/', include('blog.urls')),
    path('', include('accounts.urls')),
    path('recipes/', include('recipes.urls')),
    path('profiles/', include('profiles.urls'))
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, null=True)
    content = models.TextField()
    active = models.BooleanField(default=True)

    def get_absolute_url_detail(self):
        return reverse("article-detail", kwargs={"slug": self.slug})

    def get_absolute_url_edit(self):
        return reverse("article-edit", kwargs={"slug": self.slug})

    def get_absolute_url_delete(self):
        return reverse("article-delete", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        super(Article, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.title) + f'-{self.id}'
            self.save()

products/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=120, null=False, blank=False)
    description = models.TextField(max_length=50, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    email = models.EmailField(max_length=254, blank=True, null=True)
    featured = models.BooleanField()

    def get_absolute_url_detail(self):
        return reverse("product-detail", kwargs={"id": self.id})

    def get_absolute_url_edit(self):
        return reverse("product-edit", kwargs={"id": self.id})

    def get_absolute_url_delete(self):
        return reverse("product-delete", kwargs={"id": self.id})

recipes/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

User = settings.AUTH_USER_MODEL


class Recipe(models.Model):
    # on_delete=SET_NULL para quando deletar, o user irá  ser NULL, blank e null precisam ser True
    # on_delete=CASCADE para quando deletar, os objetos que conterem esse user, serão excluidos
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    created_at = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True)
    slug = models.SlugField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={"slug": self.slug})

    def get_absolute_url_edit(self):  # get_edit_url()
        return reverse("recipes:edit", kwargs={"slug": self.slug})

    def get_absolute_url_delete(self):  # get_delete_url()
        return reverse("recipes:delete", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        super(Recipe, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.title) + f'-{self.id}'
            self.save()

templates/about.html
{% extends 'base.html' %}

{% block content %}<h1>Templates/about.html</h1>{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .lista {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333333;
            display: flex;
            flex-direction: row;
            justify-content: center;
        }

        .lista a {
            display: block;
            color: white;
            text-decoration: none;
            text-align: center;
            padding: 16px;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }

        .lista a:hover {
            background-color: crimson;
        }

        .search-container {
            text-align: center;
            width: 300px
        }

        .search-container input[type=text] {
            padding: 10px;
            /* border: none; */
            margin: 5px;
            border-radius: 5px;
            width: 50%;
            margin-right: 5px;
        }

        .search-container button {
            background-color: crimson;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .body-content {
            border-left: 40px;
            border-right: 40px;
            border-top: 0px;
            border-bottom: 0px;
            border-style: solid;
            border-color: crimson;
        }
        .center-btn {
            text-decoration: none;
            margin: 0 auto;
            padding: 10px 20px;
            background-color: crimson;
            border: none;
            color: white;
            font-size: 14px;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <nav>
        <ul class="lista">
            <li><a href="/">Home</a></li>
            <li><a href="/contact/">Contact</a></li>
            <li><a href="/about/">About</a></li>
            <li><a href="/products/">Products</a></li>
            <li><a href="/blog/">Articles</a></li>
            <li><a href="/recipes/">Recipes</a></li>
            <form action="/search/" class="search-container">
                <input type="text" name='query' placeholder="Pesquisar...">
                <button type="submit">Search</button>
            </form>
            {% if not request.user.is_authenticated %}
            <li><a href="/login/">Login</a></li>
            <li><a href="/register/">Register</a></li>
            {% else %}
            <li><a href="/logout/">Logout</a></li>
            <li><a href="/profiles/{{ request.user }}/">My
                profile</a></li>
            {% endif %}
        </ul>
    </nav>
    <div class="body-content">
        <center>
        {% block content %}replace me{% endblock content %}
        </center>
    </div>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}<h1>Templates/contact.html</h1>{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Templates/home.html</h1>
{% endblock content %}

templates/search_result.html
{% extends 'base.html' %}


{% block content %}
<center>
<h1>Recipes:</h1>
{% for obj in recipe_list %}
    {% if obj.active %}
        <h2><a href={{ obj.get_absolute_url }}>{{ obj.title }}</a></h2>
    {% endif %}
{% endfor %}
<h1>Articles:</h1>
{% for obj in article_list %}
    <h2><a href={{ obj.get_absolute_url_detail }}>{{ obj.title }}</a></h2>
{% endfor %}
<h1>Products:</h1>
{% for obj in product_list %}
    <h2><a href={{ obj.get_absolute_url_detail }}>{{ obj.name }}</a></h2>
{% endfor %}
<h2>---> End of results <---</h2>
</center>
{% endblock content %}